[config]
schemaVersion = "0.0.1"

[package]
namespace = "Trodi"
name = "BloodyWallet"
versionNumber = "0.1.0"
description = "This framework is designed to add a virtual currency to VRising. This opens up a world of possibilities for other mods to integrate with it and serve as a bridge for other mods to use this functionality."
websiteUrl = "https://github.com/oscarpedrero/BloodyWallet"
containsNsfwContent = false

[package.dependencies]
BepInEx-BepInExPack_V_Rising = "1.691.3"
deca-VampireCommandFramework = "0.9.0"
Trodi-BloodyCore = "2.0.0"

[build]
icon = "./icon.png"
readme = "./README.md"
outdir = "./build"

[[build.copy]]
source = "./dist"
target = ""

[publish]
communities = ["v-rising"]
repository = "https://thunderstore.io"
[publish.categories]
v-rising = ["oakveil-update", "mods", "server"]